spring:
  profiles:
    active: "development"
  jackson:
    default-property-inclusion: non_null

---

spring:
  profiles: "development"
  data:
    mongodb:
      authentication-database: "admin"
      username: "root"
      password: "admin007!"
      database: "testdb"
      port: 27017
      host: "localhost"

---

spring:
  profiles: "production"